name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  DOTNET_VERSION: '8.0.x'
  PACKAGE_VERSION: 3.2.2

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Publish Nuget Package
      run: dotnet nuget push /home/runner/work/Puffix.Cqrs/Puffix.Cqrs/Puffix.Cqrs/bin/Release/Puffix.Cqrs.${{ env.PACKAGE_VERSION }}.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
